POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name":"OviniP5",
    "number": "038 234 2343"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/application/json

{}